/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stepReport.view;

import java.util.Arrays;
import stepReport.control.AdminControl;

/**
 *
 * @author Kildare
 */
public class AdminView extends javax.swing.JPanel {

    
    private AdminControl Control;

    private static int state;
    
    private static final int CADASTRO = 1;        
    private static final int BUSCA = 2;
    private static final int EDIT = 3;
    private static final int REMOVE = 4;
    
    
    /**
     * Creates new form AdminView
     * @param Control
     */
    public AdminView(AdminControl Control) {
        initComponents();
        
        this.Control = Control;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        userTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        confirmLabel = new javax.swing.JLabel();
        confirmTextField = new javax.swing.JPasswordField();
        confirmButton = new javax.swing.JToggleButton();
        cancelButton = new javax.swing.JToggleButton();
        confirmLabel2 = new javax.swing.JLabel();
        confirmTextField2 = new javax.swing.JPasswordField();

        titleLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        titleLabel.setText("Cadastrar Usuário");

        userLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        userLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userLabel.setText("Nome do usuário:");
        userLabel.setMaximumSize(new java.awt.Dimension(200, 23));
        userLabel.setMinimumSize(new java.awt.Dimension(200, 23));

        userTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        passwordLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passwordLabel.setText("Senha:");
        passwordLabel.setMaximumSize(new java.awt.Dimension(200, 23));
        passwordLabel.setMinimumSize(new java.awt.Dimension(200, 23));

        passwordTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        confirmLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        confirmLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        confirmLabel.setText("Confirmar Senha:");
        confirmLabel.setMaximumSize(new java.awt.Dimension(200, 23));
        confirmLabel.setMinimumSize(new java.awt.Dimension(200, 23));

        confirmTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        confirmButton.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        confirmButton.setText("Confirmar");
        confirmButton.setPreferredSize(new java.awt.Dimension(143, 31));
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        cancelButton.setText("Novo Usuário");
        cancelButton.setPreferredSize(new java.awt.Dimension(143, 31));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        confirmLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        confirmLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        confirmLabel2.setText("Confirmar Senha:");
        confirmLabel2.setMaximumSize(new java.awt.Dimension(200, 23));
        confirmLabel2.setMinimumSize(new java.awt.Dimension(200, 23));

        confirmTextField2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(titleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(confirmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(confirmTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(passwordTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                .addComponent(confirmTextField, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(276, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        if(AdminView.state == AdminView.CADASTRO){
            this.loadSearchView();
        }
        else if(AdminView.state == AdminView.BUSCA){
            this.loadNewView();
        }
        
        
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        if(AdminView.state == AdminView.CADASTRO){
            String user = this.userTextField.getText();
            String pass1 = new String(this.passwordTextField.getPassword());
            String pass2 = new String(this.confirmTextField.getPassword());
            if((user.length()>3) && (!pass1.isEmpty()) && (pass1.equals(pass2))){
                this.getControl().registerUser(user,pass1);
            }
            
        }
    }//GEN-LAST:event_confirmButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton cancelButton;
    private javax.swing.JToggleButton confirmButton;
    private javax.swing.JLabel confirmLabel;
    private javax.swing.JLabel confirmLabel2;
    private javax.swing.JPasswordField confirmTextField;
    private javax.swing.JPasswordField confirmTextField2;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField userTextField;
    // End of variables declaration//GEN-END:variables

    public void loadSearchView() {
        
        this.titleLabel.setText("Buscar Usuário");
        this.cancelButton.setText("Novo usuário");
        this.passwordLabel.setVisible(false);
        this.passwordTextField.setVisible(false);
        this.confirmButton.setText("Buscar");
        this.confirmLabel.setVisible(false);
        this.confirmTextField.setVisible(false);
        this.confirmLabel2.setVisible(false);
        this.confirmTextField2.setVisible(false);
        AdminView.state = AdminView.BUSCA;
    }

    public void loadNewView() {
        this.titleLabel.setText("Cadastrar Usuário");
        this.cancelButton.setText("Cancelar");
        this.passwordLabel.setVisible(true);
        this.passwordTextField.setVisible(true);
        this.confirmButton.setText("Confirmar");
        this.confirmLabel.setVisible(true);
        this.confirmTextField.setVisible(true);
        this.confirmLabel2.setVisible(false);
        this.confirmTextField2.setVisible(false);
        
        AdminView.state = AdminView.CADASTRO;
    }
    
    public AdminControl getControl() {
        return Control;
    }

    public void setControl(AdminControl Control) {
        this.Control = Control;
    }
    
    
}
