/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stepReport.view;

import stepReport.control.PeriodoControl;

/**
 *
 * @author Kildare
 */
public class PeriodoView extends javax.swing.JPanel {

    /**
     * Creates new form PeriodoView
     */
    PeriodoControl Control;
    
    public PeriodoView(PeriodoControl control) {
        initComponents();
        this.Control = control;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        funcionarioLabel = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        numeroLabel = new javax.swing.JLabel();
        numeroTextField = new javax.swing.JTextField();
        numeroLabel1 = new javax.swing.JLabel();
        numeroLabel2 = new javax.swing.JLabel();
        horasFormattedField = new javax.swing.JFormattedTextField();
        dataIniFormattedValue = new javax.swing.JFormattedTextField();
        confirmarButton = new javax.swing.JButton();
        dataFimFormattedValue1 = new javax.swing.JFormattedTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        funcionarioLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        funcionarioLabel.setText("Registrar Hora");
        add(funcionarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 13, -1, -1));

        nomeLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        nomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nomeLabel.setText("Número do trabalhador:");
        add(nomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 219, -1));

        numeroLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        numeroLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numeroLabel.setText("Horas trabalhadas:");
        add(numeroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 210, -1));

        numeroTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        add(numeroTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 78, 500, -1));

        numeroLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        numeroLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numeroLabel1.setText("Data de início de período (dd/mm/yyyy):");
        add(numeroLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        numeroLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        numeroLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numeroLabel2.setText("Data de fim de período (dd/mm/yyyy):");
        add(numeroLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 180, -1, -1));

        horasFormattedField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        horasFormattedField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        add(horasFormattedField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 500, -1));

        dataIniFormattedValue.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        dataIniFormattedValue.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        add(dataIniFormattedValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 350, -1));

        confirmarButton.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        confirmarButton.setText("Registrar");
        add(confirmarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, -1, 40));

        dataFimFormattedValue1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        dataFimFormattedValue1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        add(dataFimFormattedValue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 350, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmarButton;
    private javax.swing.JFormattedTextField dataFimFormattedValue1;
    private javax.swing.JFormattedTextField dataIniFormattedValue;
    private javax.swing.JLabel funcionarioLabel;
    private javax.swing.JFormattedTextField horasFormattedField;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JLabel numeroLabel;
    private javax.swing.JLabel numeroLabel1;
    private javax.swing.JLabel numeroLabel2;
    private javax.swing.JTextField numeroTextField;
    // End of variables declaration//GEN-END:variables
}
