/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stepReport.view;


import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sourceforge.jdatepicker.impl.JDatePanelImpl;
import net.sourceforge.jdatepicker.impl.JDatePickerImpl;
import net.sourceforge.jdatepicker.impl.UtilDateModel;
import stepReport.Util.DateLabelFormatter;
import stepReport.control.PeriodoControl;


/**
 *
 * @author Kildare
 */
public final class PeriodoView extends javax.swing.JPanel {

    /**
     * Creates new form PeriodoView
     */
    private PeriodoControl Control;
    private JDatePickerImpl DatePicker;
    
    private static int state;
    private static final int CADASTRO = 1;        
    private static final int BUSCA = 2;
    
    private static String DATA="";
    
    private static Map<String,String> funcs;
    
    public PeriodoView(PeriodoControl control) {
        initComponents();
        
        this.setControl(control);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        titleLabel = new javax.swing.JLabel();
        dataLabel = new javax.swing.JLabel();
        numeroLabel = new javax.swing.JLabel();
        diasPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SabadoHorasTextField = new javax.swing.JFormattedTextField();
        SegundaHorasTextField = new javax.swing.JFormattedTextField();
        TercaHorasTextField = new javax.swing.JFormattedTextField();
        QuartaHorasTextField = new javax.swing.JFormattedTextField();
        QuintaHorasTextField = new javax.swing.JFormattedTextField();
        SextaHorasTextField = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        DomingoHorasTextField = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        segundaUnidadeTextField = new javax.swing.JTextField();
        domingoUnidadeTextField = new javax.swing.JTextField();
        segundaNAMTextField = new javax.swing.JTextField();
        segundaBSPTextField = new javax.swing.JTextField();
        segundaTaskTextField = new javax.swing.JTextField();
        tercaTaskTextField = new javax.swing.JTextField();
        quartaTaskTextField = new javax.swing.JTextField();
        quintaTaskTextField = new javax.swing.JTextField();
        sextaTaskTextField = new javax.swing.JTextField();
        sabadoTaskTextField = new javax.swing.JTextField();
        domingoTaskTextField = new javax.swing.JTextField();
        tercaNAMTextField = new javax.swing.JTextField();
        quartaNAMTextField = new javax.swing.JTextField();
        quintaNAMTextField = new javax.swing.JTextField();
        sextaNAMTextField = new javax.swing.JTextField();
        sabadoNAMTextField = new javax.swing.JTextField();
        domingoNAMTextField = new javax.swing.JTextField();
        tercaBSPTextField = new javax.swing.JTextField();
        quartaBSPTextField = new javax.swing.JTextField();
        quintaBSPTextField = new javax.swing.JTextField();
        sextaBSPTextField = new javax.swing.JTextField();
        sabadoBSPTextField = new javax.swing.JTextField();
        domingoBSPTextField = new javax.swing.JTextField();
        tercaUnidadeTextField = new javax.swing.JTextField();
        quartaUnidadeTextField = new javax.swing.JTextField();
        quintaUnidadeTextField = new javax.swing.JTextField();
        sextaUnidadeTextField = new javax.swing.JTextField();
        sabadoUnidadeTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        confirmarButton2 = new javax.swing.JButton();
        selectedNomeLabel = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        NumeroTextField = new javax.swing.JTextField();
        NomeCombo = new javax.swing.JComboBox<>();
        initRegButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jFormattedTextField5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        jFormattedTextField5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        titleLabel.setText("Registrar Hora");
        add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 13, -1, -1));

        dataLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        dataLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dataLabel.setText("Data da semana:");
        add(dataLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 219, -1));

        numeroLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        numeroLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numeroLabel.setText("Numero do trabalhador:");
        add(numeroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 219, -1));

        diasPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        diasPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Terça-Feira:");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        diasPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Domingo:");
        diasPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 140, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Quarta-Feira:");
        diasPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Quinta-Feira:");
        diasPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 130, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Sexta-Feira:");
        diasPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 130, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setText("Segunda-Feira");
        diasPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        SabadoHorasTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        SabadoHorasTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(SabadoHorasTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 70, -1));

        SegundaHorasTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        SegundaHorasTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(SegundaHorasTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 70, -1));

        TercaHorasTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        TercaHorasTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(TercaHorasTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 70, -1));

        QuartaHorasTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        QuartaHorasTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(QuartaHorasTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 70, -1));

        QuintaHorasTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        QuintaHorasTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(QuintaHorasTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 70, -1));

        SextaHorasTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        SextaHorasTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(SextaHorasTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 70, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Sábado:");
        diasPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 130, -1));

        DomingoHorasTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        DomingoHorasTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(DomingoHorasTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 70, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel8.setText("Unidade");
        diasPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel9.setText("Dia");
        diasPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel10.setText("NAM");
        diasPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel11.setText("BSP");
        diasPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        segundaUnidadeTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(segundaUnidadeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 110, -1));

        domingoUnidadeTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(domingoUnidadeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 110, -1));

        segundaNAMTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(segundaNAMTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 110, -1));

        segundaBSPTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(segundaBSPTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 110, -1));

        segundaTaskTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(segundaTaskTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 110, -1));

        tercaTaskTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(tercaTaskTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 110, -1));

        quartaTaskTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(quartaTaskTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 110, -1));

        quintaTaskTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(quintaTaskTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 110, -1));

        sextaTaskTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(sextaTaskTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 110, -1));

        sabadoTaskTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(sabadoTaskTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 110, -1));

        domingoTaskTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(domingoTaskTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 110, -1));

        tercaNAMTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(tercaNAMTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 110, -1));

        quartaNAMTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(quartaNAMTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 110, -1));

        quintaNAMTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(quintaNAMTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 110, -1));

        sextaNAMTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(sextaNAMTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 110, -1));

        sabadoNAMTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(sabadoNAMTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 110, -1));

        domingoNAMTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(domingoNAMTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 110, -1));

        tercaBSPTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(tercaBSPTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 110, -1));

        quartaBSPTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(quartaBSPTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 110, -1));

        quintaBSPTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(quintaBSPTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 110, -1));

        sextaBSPTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(sextaBSPTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 110, -1));

        sabadoBSPTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(sabadoBSPTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 110, -1));

        domingoBSPTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(domingoBSPTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 110, -1));

        tercaUnidadeTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(tercaUnidadeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 110, -1));

        quartaUnidadeTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(quartaUnidadeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 110, -1));

        quintaUnidadeTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(quintaUnidadeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 110, -1));

        sextaUnidadeTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(sextaUnidadeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 110, -1));

        sabadoUnidadeTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(sabadoUnidadeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, 110, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel12.setText("Task");
        diasPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, 20));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel13.setText("Horas");
        diasPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        confirmarButton2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        confirmarButton2.setText("Registrar");
        confirmarButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarButton2ActionPerformed(evt);
            }
        });
        diasPanel.add(confirmarButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 340, -1, 40));

        add(diasPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 770, 390));

        selectedNomeLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        selectedNomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        selectedNomeLabel.setText("Nome do trabalhador:");
        add(selectedNomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 120, -1));

        nomeLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        nomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nomeLabel.setText("Nome do trabalhador:");
        add(nomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 219, -1));

        NumeroTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        add(NumeroTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 380, -1));

        NomeCombo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        NomeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeComboActionPerformed(evt);
            }
        });
        add(NomeCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 380, -1));

        initRegButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        initRegButton.setText("Iniciar Registro");
        initRegButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initRegButtonActionPerformed(evt);
            }
        });
        add(initRegButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 160, -1));

        jButton1.setText("Buscar por Numero");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, -1, -1));

        jButton2.setText("Buscar Nomes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarButton2ActionPerformed
        // TODO add your handling code here:
        boolean isOK=true;
        if(PeriodoView.DATA.equals(""))
        {
            JOptionPane.showMessageDialog(new JFrame(), "Erro no registro de hora, realizar novamente");
        }
        if(!this.DatePicker.getJFormattedTextField().getText().equals(PeriodoView.DATA))
        {
            isOK=false;
            int opt = JOptionPane.showConfirmDialog(new JFrame(), "ATENÇÃO: A data original foi modificada. A alocação será feita para o dia "+PeriodoView.DATA +". Confirma?");
            if(opt!=JOptionPane.OK_OPTION)
                isOK=true;
        }
        
        if(isOK)
        {
            if(this.isValidAlocacao())
            {
                //Preciso ajustar a hora caso o formato do mes esteja em caracteres de 3 letras ao inves de 2 numeros

                System.out.println("Log da data: "+PeriodoView.DATA); 
                if(this.getControl().createCadastro(this.NumeroTextField.getText(), PeriodoView.DATA, this.getAlocacao()))
                    JOptionPane.showMessageDialog(new JFrame(), "Cadastro de horas realizado com sucesso");
                else
                    JOptionPane.showMessageDialog(new JFrame(),"Erro no cadastro das horas");
            }
        }
        else
            this.initRegisterView();
        
    }//GEN-LAST:event_confirmarButton2ActionPerformed

    private void NomeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeComboActionPerformed
        setNummeroDoNome();
    }//GEN-LAST:event_NomeComboActionPerformed
    
    public void setNummeroDoNome(){
        this.NumeroTextField.setText(PeriodoView.funcs.get((String)this.NomeCombo.getSelectedItem()));
    }
    
    private void initRegButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initRegButtonActionPerformed
        // TODO add your handling code here:
        setNummeroDoNome();
        if(this.DatePicker.getJFormattedTextField().getText().isEmpty())
            JOptionPane.showMessageDialog(new JFrame(), "Nenhuma data selecionada.");
        
        else if(this.isValidDate())
        {
            String[] date = this.DatePicker.getJFormattedTextField().getText().split("/");
            if(this.getControl().isAvailableWeek(this.NumeroTextField.getText(),date[2]+date[1]+date[0])){
                this.NomeCombo.setVisible(false);
                this.NumeroTextField.setEditable(false);
                this.jButton1.setEnabled(false);
                this.jButton2.setEnabled(false);
                this.selectedNomeLabel.setText((String)this.NomeCombo.getSelectedItem());
                this.selectedNomeLabel.setVisible(true);
                PeriodoView.DATA=this.DatePicker.getJFormattedTextField().getText();
                this.diasPanel.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(new JFrame(), "A Semana escolhida ja esta alocada para o funcionario " + (String)this.NomeCombo.getSelectedItem() + ".");
                this.diasPanel.setVisible(false);
            }
        }
        else
        {
            this.initRegisterView();
        }
        
    }//GEN-LAST:event_initRegButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.NomeCombo.setVisible(true);
        String nomeFuncionario = null;
        if(this.NumeroTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(new JFrame(), "Nenhum numero digitado");
        }else{
            nomeFuncionario = this.getControl().getUserName(this.NumeroTextField.getText());
        }

        if(nomeFuncionario != null){
            this.NomeCombo.removeAllItems();
            this.NomeCombo.addItem(nomeFuncionario);
            iniciandoComponentes();
        }else{
            JOptionPane.showMessageDialog(new JFrame(), "Nenhum funcionario com esse numero");
        }
        
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.NumeroTextField.setText("");
        if(!this.loadComboNames())
        {
            this.getControl().loadFuncionarioView();
        }
        initRegisterView();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField DomingoHorasTextField;
    private javax.swing.JComboBox<String> NomeCombo;
    private javax.swing.JTextField NumeroTextField;
    private javax.swing.JFormattedTextField QuartaHorasTextField;
    private javax.swing.JFormattedTextField QuintaHorasTextField;
    private javax.swing.JFormattedTextField SabadoHorasTextField;
    private javax.swing.JFormattedTextField SegundaHorasTextField;
    private javax.swing.JFormattedTextField SextaHorasTextField;
    private javax.swing.JFormattedTextField TercaHorasTextField;
    private javax.swing.JButton confirmarButton2;
    private javax.swing.JLabel dataLabel;
    private javax.swing.JPanel diasPanel;
    private javax.swing.JTextField domingoBSPTextField;
    private javax.swing.JTextField domingoNAMTextField;
    private javax.swing.JTextField domingoTaskTextField;
    private javax.swing.JTextField domingoUnidadeTextField;
    private javax.swing.JButton initRegButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JLabel numeroLabel;
    private javax.swing.JTextField quartaBSPTextField;
    private javax.swing.JTextField quartaNAMTextField;
    private javax.swing.JTextField quartaTaskTextField;
    private javax.swing.JTextField quartaUnidadeTextField;
    private javax.swing.JTextField quintaBSPTextField;
    private javax.swing.JTextField quintaNAMTextField;
    private javax.swing.JTextField quintaTaskTextField;
    private javax.swing.JTextField quintaUnidadeTextField;
    private javax.swing.JTextField sabadoBSPTextField;
    private javax.swing.JTextField sabadoNAMTextField;
    private javax.swing.JTextField sabadoTaskTextField;
    private javax.swing.JTextField sabadoUnidadeTextField;
    private javax.swing.JTextField segundaBSPTextField;
    private javax.swing.JTextField segundaNAMTextField;
    private javax.swing.JTextField segundaTaskTextField;
    private javax.swing.JTextField segundaUnidadeTextField;
    private javax.swing.JLabel selectedNomeLabel;
    private javax.swing.JTextField sextaBSPTextField;
    private javax.swing.JTextField sextaNAMTextField;
    private javax.swing.JTextField sextaTaskTextField;
    private javax.swing.JTextField sextaUnidadeTextField;
    private javax.swing.JTextField tercaBSPTextField;
    private javax.swing.JTextField tercaNAMTextField;
    private javax.swing.JTextField tercaTaskTextField;
    private javax.swing.JTextField tercaUnidadeTextField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
    
    
    
    public void insertDatePicker(){
        UtilDateModel model = new UtilDateModel();
        JDatePanelImpl datePanel = new JDatePanelImpl(model);
        this.DatePicker = new JDatePickerImpl(datePanel,new DateLabelFormatter());
        this.DatePicker.getJFormattedTextField().setFont(new java.awt.Font("Verdana",0,18));
        this.add(DatePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160));
    }
    
    
    public boolean isValidDataSemana(String dataSemana){
        
        if(dataSemana.equals(""))
            return false;
        
        Calendar c = Calendar.getInstance();
        String ano =dataSemana.substring(6, 10); 
        String mes = dataSemana.substring(3, 5);
        String dia = dataSemana.substring(0, 2);
        
        c.set(Integer.parseInt(ano), Integer.parseInt(mes)-1, Integer.parseInt(dia));
        int semana = c.get(Calendar.DAY_OF_WEEK);
        if(semana != Calendar.SUNDAY){
            return false; 
        }
        else
            return true;
    }

    
    public void initRegisterView() {
        
        PeriodoView.DATA="";
        this.selectedNomeLabel.setVisible(false);
        this.NomeCombo.setVisible(true);
        this.NumeroTextField.setEditable(true);
        
        iniciandoComponentes();
        
    }
    
    protected void iniciandoComponentes(){
        
        this.jButton1.setEnabled(true);
        this.jButton2.setEnabled(true);
        this.DatePicker.setButtonFocusable(true);
        this.DatePicker.getJFormattedTextField().setText("");
        this.DatePicker.setVisible(true);
        this.titleLabel.setText("Registrar hora");
        this.diasPanel.setVisible(false);
        this.DomingoHorasTextField.setText("");
        this.SabadoHorasTextField.setText("");
        this.SegundaHorasTextField.setText("");
        this.TercaHorasTextField.setText("");
        this.QuartaHorasTextField.setText("");
        this.QuintaHorasTextField.setText("");
        this.SextaHorasTextField.setText("");
        this.segundaTaskTextField.setText("");
        this.segundaNAMTextField.setText("");
        this.segundaUnidadeTextField.setText("");
        this.segundaBSPTextField.setText("");
        this.tercaTaskTextField.setText("");
        this.tercaNAMTextField.setText("");
        this.tercaUnidadeTextField.setText("");
        this.tercaBSPTextField.setText("");
        this.quartaTaskTextField.setText("");
        this.quartaNAMTextField.setText("");
        this.quartaUnidadeTextField.setText("");
        this.quartaBSPTextField.setText("");
        this.quintaTaskTextField.setText("");
        this.quintaNAMTextField.setText("");
        this.quintaUnidadeTextField.setText("");
        this.quintaBSPTextField.setText("");
        this.sextaTaskTextField.setText("");
        this.sextaNAMTextField.setText("");
        this.sextaUnidadeTextField.setText("");
        this.sextaBSPTextField.setText("");
        this.sabadoTaskTextField.setText("");
        this.sabadoNAMTextField.setText("");
        this.sabadoUnidadeTextField.setText("");
        this.sabadoBSPTextField.setText("");
        this.domingoTaskTextField.setText("");
        this.domingoNAMTextField.setText("");
        this.domingoUnidadeTextField.setText("");
        this.domingoBSPTextField.setText("");
        
        PeriodoView.state = PeriodoView.BUSCA;
    }
    
    
     public PeriodoControl getControl() 
     {
        return Control;
     }

    public void setControl(PeriodoControl Control) {
        this.Control = Control;
    }

    private Map<String, List<String>> getAlocacao() 
    {
        Map<String,List<String>> horas = new HashMap<String,List<String>>();
        
        List<String> segunda = new ArrayList<String>();
        segunda.add(this.SegundaHorasTextField.getText());
        segunda.add(this.segundaTaskTextField.getText());
        segunda.add(this.segundaNAMTextField.getText());
        segunda.add(this.segundaBSPTextField.getText());
        segunda.add(this.segundaUnidadeTextField.getText());
        horas.put("seg", segunda);
        List<String> terca = new ArrayList<String>();
        terca.add(this.TercaHorasTextField.getText());
        terca.add(this.tercaTaskTextField.getText());
        terca.add(this.tercaNAMTextField.getText());
        terca.add(this.tercaBSPTextField.getText());
        terca.add(this.tercaUnidadeTextField.getText());
        horas.put("ter", terca);
        List<String> quarta = new ArrayList<String>();
        quarta.add(this.QuartaHorasTextField.getText());
        quarta.add(this.quartaTaskTextField.getText());
        quarta.add(this.quartaNAMTextField.getText());
        quarta.add(this.quartaBSPTextField.getText());
        quarta.add(this.quartaUnidadeTextField.getText());
        horas.put("qua", quarta);
        List<String> quinta = new ArrayList<String>();
        quinta.add(this.QuintaHorasTextField.getText());
        quinta.add(this.quintaTaskTextField.getText());
        quinta.add(this.quintaNAMTextField.getText());
        quinta.add(this.quintaBSPTextField.getText());
        quinta.add(this.quintaUnidadeTextField.getText());
        horas.put("qui", quinta);
        List<String> sexta = new ArrayList<String>();
        sexta.add(this.SextaHorasTextField.getText());
        sexta.add(this.sextaTaskTextField.getText());
        sexta.add(this.sextaNAMTextField.getText());
        sexta.add(this.sextaBSPTextField.getText());
        sexta.add(this.sextaUnidadeTextField.getText());
        horas.put("sex", sexta);
        List<String> sabado = new ArrayList<String>();
        sabado.add(this.SabadoHorasTextField.getText());
        sabado.add(this.sabadoTaskTextField.getText());
        sabado.add(this.sabadoNAMTextField.getText());
        sabado.add(this.sabadoBSPTextField.getText());
        sabado.add(this.sabadoUnidadeTextField.getText());
        horas.put("sab", sabado);
        List<String> domingo = new ArrayList<String>();
        domingo.add(this.DomingoHorasTextField.getText());
        domingo.add(this.domingoTaskTextField.getText());
        domingo.add(this.domingoNAMTextField.getText());
        domingo.add(this.domingoBSPTextField.getText());
        domingo.add(this.domingoUnidadeTextField.getText());
        horas.put("dom", domingo);
        
        return horas;
    }
    
    private boolean isValidDate()
    {
        if(this.DatePicker.getJFormattedTextField().getText().equals("")){
            JOptionPane.showMessageDialog(new JFrame(), "Nenhuma data selecionada");
            return false;
        }
        if(!validDate())
        {
            JOptionPane.showMessageDialog(new JFrame(), "Data selecionada Inválida");
            return false;
        }
        return true;
    }

    private boolean isValidAlocacao() {
        
        int horas;
            
        try{
            horas = Integer.parseInt(this.SegundaHorasTextField.getText());
            if(horas<0||horas>24 || (this.segundaNAMTextField.getText().equals("") && this.segundaTaskTextField.getText().equals(""))){
                JOptionPane.showMessageDialog(new JFrame(), "Alocação de Segunda Inválida");
                return false;
            }
            horas = Integer.parseInt(this.TercaHorasTextField.getText());
            if(horas<0||horas>24  || (this.tercaNAMTextField.getText().equals("") && this.tercaTaskTextField.getText().equals("")))
            {
                JOptionPane.showMessageDialog(new JFrame(), "Alocação de Terça Inválida");
                return false;
            }
            horas = Integer.parseInt(this.QuartaHorasTextField.getText());
            if(horas<0||horas>24 || (this.quartaNAMTextField.getText().equals("") && this.quartaTaskTextField.getText().equals("")))
            {
                JOptionPane.showMessageDialog(new JFrame(), "Alocação de Quarta Inválida");
                return false;
            }
            horas = Integer.parseInt(this.QuintaHorasTextField.getText());
            if(horas<0||horas>24 || (this.quintaNAMTextField.getText().equals("") && this.quintaTaskTextField.getText().equals("")))
            {
                JOptionPane.showMessageDialog(new JFrame(), "Alocação de Quinta Inválida");
                return false;
            }

            horas = Integer.parseInt(this.SextaHorasTextField.getText());
            if(horas<0||horas>24 || (this.sextaNAMTextField.getText().equals("") && this.sextaTaskTextField.getText().equals(""))){
                JOptionPane.showMessageDialog(new JFrame(), "Alocação de Sexta Inválida");
                return false;
            }
            horas = Integer.parseInt(this.SabadoHorasTextField.getText());
            if(horas<0||horas>24 || (this.sabadoNAMTextField.getText().equals("") && this.sabadoTaskTextField.getText().equals(""))){
                JOptionPane.showMessageDialog(new JFrame(), "Alocação de Sábado Inválida");
                return false;
            }
            horas = Integer.parseInt(this.DomingoHorasTextField.getText());
            if(horas<0||horas>24 || (this.domingoNAMTextField.getText().equals("") && this.domingoTaskTextField.getText().equals("")))
            {
                JOptionPane.showMessageDialog(new JFrame(), "Alocação de Domingo Inválida");
                return false;
            }
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(new JFrame(), "Existem alocações de horas vazias");
            return false;
        }
        return true;
        
    }

    private boolean loadComboNames() {
        
        this.NomeCombo.removeAllItems();
        PeriodoView.funcs = this.getControl().getFuncNameNumber();
        if(PeriodoView.funcs.isEmpty()){
            JOptionPane.showMessageDialog(new JFrame(), "Nao ha funcionarios para cadastrar");
            return false;
        }
        else
        {
            for(String str : PeriodoView.funcs.keySet())
                this.NomeCombo.addItem(str);
            return true;
        }
        
    }
    
    private boolean validDate() {
         String ini = this.DatePicker.getJFormattedTextField().getText();
        if(ini.equals(""))
            return false;
        
        Calendar c = Calendar.getInstance();
        c.set(Integer.parseInt(ini.substring(6, 10)), Integer.parseInt(ini.substring(3, 5))-1, Integer.parseInt(ini.substring(0, 2)));
        if(c.get(Calendar.DAY_OF_WEEK) != Calendar.SUNDAY)
            return false;
       
        return true;
    }

    
}

