/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stepReport.view;


import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sourceforge.jdatepicker.impl.JDatePanelImpl;
import net.sourceforge.jdatepicker.impl.JDatePickerImpl;
import net.sourceforge.jdatepicker.impl.UtilDateModel;
import stepReport.control.PeriodoControl;


/**
 *
 * @author Kildare
 */
public final class PeriodoView extends javax.swing.JPanel {

    /**
     * Creates new form PeriodoView
     */
    private PeriodoControl Control;
    private JDatePickerImpl DatePicker;
    
    private static int state;
    private static final int CADASTRO = 1;        
    private static final int BUSCA = 2;
    
    
    public PeriodoView(PeriodoControl control) {
        initComponents();
        
        this.setControl(control);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        titleLabel = new javax.swing.JLabel();
        dataLabel = new javax.swing.JLabel();
        confirmarButton = new javax.swing.JButton();
        nomeLabel1 = new javax.swing.JLabel();
        diasPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SabadoHorasTextField = new javax.swing.JFormattedTextField();
        SegundaHorasTextField = new javax.swing.JFormattedTextField();
        TercaHorasTextField = new javax.swing.JFormattedTextField();
        QuartaHorasTextField = new javax.swing.JFormattedTextField();
        QuintaHorasTextField = new javax.swing.JFormattedTextField();
        SextaHorasTextField = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        DomingoHorasTextField = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        segundaUnidadeTextField = new javax.swing.JTextField();
        domingoUnidadeTextField = new javax.swing.JTextField();
        segundaNAMTextField = new javax.swing.JTextField();
        segundaBSPTextField = new javax.swing.JTextField();
        segundaTaskTextField = new javax.swing.JTextField();
        tercaTaskTextField = new javax.swing.JTextField();
        quartaTaskTextField = new javax.swing.JTextField();
        quintaTaskTextField = new javax.swing.JTextField();
        sextaTaskTextField = new javax.swing.JTextField();
        sabadoTaskTextField = new javax.swing.JTextField();
        domingoTaskTextField = new javax.swing.JTextField();
        tercaNAMTextField = new javax.swing.JTextField();
        quartaNAMTextField = new javax.swing.JTextField();
        quintaNAMTextField = new javax.swing.JTextField();
        sextaNAMTextField = new javax.swing.JTextField();
        sabadoNAMTextField = new javax.swing.JTextField();
        domingoNAMTextField = new javax.swing.JTextField();
        tercaBSPTextField = new javax.swing.JTextField();
        quartaBSPTextField = new javax.swing.JTextField();
        quintaBSPTextField = new javax.swing.JTextField();
        sextaBSPTextField = new javax.swing.JTextField();
        sabadoBSPTextField = new javax.swing.JTextField();
        domingoBSPTextField = new javax.swing.JTextField();
        tercaUnidadeTextField = new javax.swing.JTextField();
        quartaUnidadeTextField = new javax.swing.JTextField();
        quintaUnidadeTextField = new javax.swing.JTextField();
        sextaUnidadeTextField = new javax.swing.JTextField();
        sabadoUnidadeTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        numeroTextField = new javax.swing.JFormattedTextField();

        jFormattedTextField5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        jFormattedTextField5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        titleLabel.setText("Registrar Hora");
        add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 13, -1, -1));

        dataLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        dataLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dataLabel.setText("Data da semana:");
        add(dataLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 219, -1));

        confirmarButton.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        confirmarButton.setText("Registrar");
        confirmarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarButtonActionPerformed(evt);
            }
        });
        add(confirmarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, -1, 40));

        nomeLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        nomeLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nomeLabel1.setText("Número do trabalhador:");
        add(nomeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 219, -1));

        diasPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        diasPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Terça-Feira:");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        diasPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Domingo:");
        diasPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 140, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Quarta-Feira:");
        diasPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Quinta-Feira:");
        diasPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 130, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Sexta-Feira:");
        diasPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 130, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setText("Segunda-Feira");
        diasPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        SabadoHorasTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        SabadoHorasTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(SabadoHorasTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 70, -1));

        SegundaHorasTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        SegundaHorasTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(SegundaHorasTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 70, -1));

        TercaHorasTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        TercaHorasTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(TercaHorasTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 70, -1));

        QuartaHorasTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        QuartaHorasTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(QuartaHorasTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 70, -1));

        QuintaHorasTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        QuintaHorasTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(QuintaHorasTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 70, -1));

        SextaHorasTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        SextaHorasTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(SextaHorasTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 70, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Sábado:");
        diasPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 130, -1));

        DomingoHorasTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        DomingoHorasTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(DomingoHorasTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 70, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel8.setText("Unidade");
        diasPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel9.setText("Dia");
        diasPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel10.setText("NAM");
        diasPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel11.setText("BSP");
        diasPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        segundaUnidadeTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(segundaUnidadeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 110, -1));

        domingoUnidadeTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(domingoUnidadeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 110, -1));

        segundaNAMTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(segundaNAMTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 110, -1));

        segundaBSPTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(segundaBSPTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 110, -1));

        segundaTaskTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(segundaTaskTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 110, -1));

        tercaTaskTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(tercaTaskTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 110, -1));

        quartaTaskTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(quartaTaskTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 110, -1));

        quintaTaskTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(quintaTaskTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 110, -1));

        sextaTaskTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(sextaTaskTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 110, -1));

        sabadoTaskTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(sabadoTaskTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 110, -1));

        domingoTaskTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(domingoTaskTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 110, -1));

        tercaNAMTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(tercaNAMTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 110, -1));

        quartaNAMTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(quartaNAMTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 110, -1));

        quintaNAMTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(quintaNAMTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 110, -1));

        sextaNAMTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(sextaNAMTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 110, -1));

        sabadoNAMTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(sabadoNAMTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 110, -1));

        domingoNAMTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(domingoNAMTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 110, -1));

        tercaBSPTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(tercaBSPTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 110, -1));

        quartaBSPTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(quartaBSPTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 110, -1));

        quintaBSPTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(quintaBSPTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 110, -1));

        sextaBSPTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(sextaBSPTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 110, -1));

        sabadoBSPTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(sabadoBSPTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 110, -1));

        domingoBSPTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(domingoBSPTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 110, -1));

        tercaUnidadeTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(tercaUnidadeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 110, -1));

        quartaUnidadeTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(quartaUnidadeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 110, -1));

        quintaUnidadeTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(quintaUnidadeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 110, -1));

        sextaUnidadeTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(sextaUnidadeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 110, -1));

        sabadoUnidadeTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        diasPanel.add(sabadoUnidadeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, 110, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel12.setText("Task");
        diasPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, 20));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel13.setText("Horas");
        diasPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        add(diasPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 770, 350));

        numeroTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        numeroTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        add(numeroTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 420, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarButtonActionPerformed
        // TODO add your handling code here:
        
        if(PeriodoView.state == PeriodoView.BUSCA){
            String numeroFunc = this.numeroTextField.getText();
            String data = this.DatePicker.getJFormattedTextField().getText();
            String hrDom = this.DomingoHorasTextField.getText();
            String hrSeg = this.SegundaHorasTextField.getText();
            String hrTer = this.TercaHorasTextField.getText();
            String hrQua = this.QuartaHorasTextField.getText();
            String hrQui= this.QuintaHorasTextField.getText();
            String hrSex = this.SextaHorasTextField.getText();
            String hrSab = this.SabadoHorasTextField.getText();
            
            if(numeroFunc.equals("")){
                JOptionPane.showMessageDialog(new JFrame(), "Fornecer número do funcionário");
            }
            else if(data.equals("")){
                JOptionPane.showMessageDialog(new JFrame(), "Fornecer data da semana");
            }
            else{ 
                //TODO fazer tratamento da data
                //Calendar c = Calendar.getInstance();
                //c.
                if(!this.isValidDataSemana(data))
                    JOptionPane.showMessageDialog(new JFrame(), "Escolha um domingo para data da semana");
                else{
                    String str = data.replace("/", "");
                    str = str.substring(4, 8) + str.substring(2, 4) + str.substring(0, 2);
                    ArrayList<String> resultado = this.Control.searchTarefa(numeroFunc,str);
                    if(resultado == null)
                    {
                        if(this.Control.createCadastro(numeroFunc, str, hrDom, hrSeg, hrTer, hrQua, hrQui, hrSex, hrSab))
                            JOptionPane.showMessageDialog(new JFrame(), "Cadastrao realizado com sucesso");
                        else
                        {
                            JOptionPane.showMessageDialog(new JFrame(), "Erro no cadastro de horas");
                        } 
                    }
                    else{
                        JOptionPane.showMessageDialog(new JFrame(), "Cadastro de horas ja existente");
                    }
                }
            }
        }
        
        else if(PeriodoView.state == PeriodoView.CADASTRO){
            String numeroFunc = this.numeroTextField.getText();
            String data = this.DatePicker.getJFormattedTextField().getText();
            String hrDom = this.DomingoHorasTextField.getText();
            String hrSeg = this.SegundaHorasTextField.getText();
            String hrTer = this.TercaHorasTextField.getText();
            String hrQua = this.QuartaHorasTextField.getText();
            String hrQui= this.QuintaHorasTextField.getText();
            String hrSex = this.SextaHorasTextField.getText();
            String hrSab = this.SabadoHorasTextField.getText();
            
            if(!this.isValidDataSemana(data))
                JOptionPane.showMessageDialog(new JFrame(), "Escolha um domingo para data da semana");
            
            else if(this.getControl().createCadastro(numeroFunc, data, hrDom, hrSeg, hrTer, hrQua, hrQui, hrSex, hrSab)){
                JOptionPane.showMessageDialog(new JFrame(), "Cadastro de horas realizado com sucesso");   
            }
            else{
                JOptionPane.showMessageDialog(new JFrame(), "Erro no cadastro de horas");   
            }
        }
        
        
    }//GEN-LAST:event_confirmarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField DomingoHorasTextField;
    private javax.swing.JFormattedTextField QuartaHorasTextField;
    private javax.swing.JFormattedTextField QuintaHorasTextField;
    private javax.swing.JFormattedTextField SabadoHorasTextField;
    private javax.swing.JFormattedTextField SegundaHorasTextField;
    private javax.swing.JFormattedTextField SextaHorasTextField;
    private javax.swing.JFormattedTextField TercaHorasTextField;
    private javax.swing.JButton confirmarButton;
    private javax.swing.JLabel dataLabel;
    private javax.swing.JPanel diasPanel;
    private javax.swing.JTextField domingoBSPTextField;
    private javax.swing.JTextField domingoNAMTextField;
    private javax.swing.JTextField domingoTaskTextField;
    private javax.swing.JTextField domingoUnidadeTextField;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel nomeLabel1;
    private javax.swing.JFormattedTextField numeroTextField;
    private javax.swing.JTextField quartaBSPTextField;
    private javax.swing.JTextField quartaNAMTextField;
    private javax.swing.JTextField quartaTaskTextField;
    private javax.swing.JTextField quartaUnidadeTextField;
    private javax.swing.JTextField quintaBSPTextField;
    private javax.swing.JTextField quintaNAMTextField;
    private javax.swing.JTextField quintaTaskTextField;
    private javax.swing.JTextField quintaUnidadeTextField;
    private javax.swing.JTextField sabadoBSPTextField;
    private javax.swing.JTextField sabadoNAMTextField;
    private javax.swing.JTextField sabadoTaskTextField;
    private javax.swing.JTextField sabadoUnidadeTextField;
    private javax.swing.JTextField segundaBSPTextField;
    private javax.swing.JTextField segundaNAMTextField;
    private javax.swing.JTextField segundaTaskTextField;
    private javax.swing.JTextField segundaUnidadeTextField;
    private javax.swing.JTextField sextaBSPTextField;
    private javax.swing.JTextField sextaNAMTextField;
    private javax.swing.JTextField sextaTaskTextField;
    private javax.swing.JTextField sextaUnidadeTextField;
    private javax.swing.JTextField tercaBSPTextField;
    private javax.swing.JTextField tercaNAMTextField;
    private javax.swing.JTextField tercaTaskTextField;
    private javax.swing.JTextField tercaUnidadeTextField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

    public void insertDatePicker(){
        UtilDateModel model = new UtilDateModel();
        JDatePanelImpl datePanel = new JDatePanelImpl(model);
        this.DatePicker = new JDatePickerImpl(datePanel);
        this.DatePicker.getJFormattedTextField().setFont(new java.awt.Font("Verdana",0,18));
        this.add(DatePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140));
    }
    
    
    public boolean isValidDataSemana(String dataSemana){
        Calendar c = Calendar.getInstance();
        String ano =dataSemana.substring(6, 10); 
        String mes = dataSemana.substring(3, 5);
        String dia = dataSemana.substring(0, 2);
        
        c.set(Integer.parseInt(ano), Integer.parseInt(mes)-1, Integer.parseInt(dia));
        int semana = c.get(Calendar.DAY_OF_WEEK);
        if(semana != Calendar.SUNDAY){
            return false; 
        }
        else
            return true;
    }

    public void initSearchView() {
        
        this.DatePicker.getJFormattedTextField().setText("");
        this.DatePicker.setVisible(true);
        this.titleLabel.setText("Ver Hora");
        this.numeroTextField.setText("");
        this.numeroTextField.setEditable(true);
        this.diasPanel.setVisible(false);
        PeriodoView.state = PeriodoView.BUSCA;
        
        
    }
    
    public void initRegisterView() {
        this.DatePicker.getJFormattedTextField().setText("");
        this.DatePicker.setVisible(true);
        this.titleLabel.setText("Registrar hora");
        this.numeroTextField.setText("");
        this.numeroTextField.setEditable(true);
        this.diasPanel.setVisible(true);
        this.DomingoHorasTextField.setText("");
        this.SabadoHorasTextField.setText("");
        this.SegundaHorasTextField.setText("");
        this.TercaHorasTextField.setText("");
        this.QuartaHorasTextField.setText("");
        this.QuintaHorasTextField.setText("");
        this.SextaHorasTextField.setText("");
        this.segundaTaskTextField.setText("");
        this.segundaNAMTextField.setText("");
        this.segundaUnidadeTextField.setText("");
        this.segundaBSPTextField.setText("");
        this.tercaTaskTextField.setText("");
        this.tercaNAMTextField.setText("");
        this.tercaUnidadeTextField.setText("");
        this.tercaBSPTextField.setText("");
        this.quartaTaskTextField.setText("");
        this.quartaNAMTextField.setText("");
        this.quartaUnidadeTextField.setText("");
        this.quartaBSPTextField.setText("");
        this.quintaTaskTextField.setText("");
        this.quintaNAMTextField.setText("");
        this.quintaUnidadeTextField.setText("");
        this.quintaBSPTextField.setText("");
        this.sextaTaskTextField.setText("");
        this.sextaNAMTextField.setText("");
        this.sextaUnidadeTextField.setText("");
        this.sextaBSPTextField.setText("");
        this.sabadoTaskTextField.setText("");
        this.sabadoNAMTextField.setText("");
        this.sabadoUnidadeTextField.setText("");
        this.sabadoBSPTextField.setText("");
        this.domingoTaskTextField.setText("");
        this.domingoNAMTextField.setText("");
        this.domingoUnidadeTextField.setText("");
        this.domingoBSPTextField.setText("");
        
        PeriodoView.state = PeriodoView.BUSCA;
    }
    
    
     public PeriodoControl getControl() {
        return Control;
    }

    public void setControl(PeriodoControl Control) {
        this.Control = Control;
    }

    
}

